title: Arjun Subhash
description: Computational Chemistry | DFT | Machine Learning
theme: minima

author:
  name: Arjun Subhash
  email: arjunsubhash33@gmail.com

github_username: arjunsubhashmr
linkedin_username: arjunsubhash
